[package]
name = "bynamo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
async-channel = "2.0.0"
async-trait = "0.1.74"
byteorder = "1.5.0"
fasthash = "0.4.0"
futures = "0.3.28"
log = "0.4.20"
log-derive = "0.4.1"
rand = "0.8.5"
stopwatch = "0.0.7"
thiserror = "1.0.50"
tokio = { version = "1.33.0", features = ["full"] }

[[bin]]
name = "main"
path = "src/main.rs"
