{
 "title": "Bynamo",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Item Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Puts/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(putitem_histogram_count[10s])) by (node)",
     "legendFormat": "Node {{node}}"
    }
   ]
  },
  {
   "title": "Put Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(putitem_histogram_bucket[1m])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(putitem_histogram_bucket[1m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.999, sum by (le) (rate(putitem_histogram_bucket[1m])))",
     "legendFormat": "P99.9"
    },
    {
     "expr": "histogram_quantile(1, sum by (le) (rate(putitem_histogram_bucket[1m])))",
     "legendFormat": "P100"
    }
   ]
  },
  {
   "title": "Put backoffs/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(node_store_buffer_backoffs_histogram_count[10s])) by (node)",
     "legendFormat": "Node {{node}}"
    }
   ]
  },
  {
   "title": "Put Buffer Backoff Sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(node_store_buffer_backoffs_histogram_bucket[1m])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(node_store_buffer_backoffs_histogram_bucket[1m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.999, sum by (le) (rate(node_store_buffer_backoffs_histogram_bucket[1m])))",
     "legendFormat": "P99.9"
    },
    {
     "expr": "histogram_quantile(1, sum by (le) (rate(node_store_buffer_backoffs_histogram_bucket[1m])))",
     "legendFormat": "P100"
    }
   ]
  },
  {
   "title": "Put Round Trip Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(putitem_round_trip_histogram_bucket[1m])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(putitem_round_trip_histogram_bucket[1m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.999, sum by (le) (rate(putitem_round_trip_histogram_bucket[1m])))",
     "legendFormat": "P99.9"
    },
    {
     "expr": "histogram_quantile(1, sum by (le) (rate(putitem_round_trip_histogram_bucket[1m])))",
     "legendFormat": "P100"
    }
   ]
  },
  { "title": "Write Ahead Log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Writes/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(wal_writes_histogram_count[10s])) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Writes Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(wal_writes_histogram_bucket[1m])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(wal_writes_histogram_bucket[1m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.999, sum by (le) (rate(wal_writes_histogram_bucket[1m])))",
     "legendFormat": "P99.9"
    },
    {
     "expr": "histogram_quantile(1, sum by (le) (rate(wal_writes_histogram_bucket[1m])))",
     "legendFormat": "P100"
    }
   ]
  },
  {
   "title": "Flush Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(wal_buffer_flush_histogram_bucket[1m])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(wal_buffer_flush_histogram_bucket[1m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.999, sum by (le) (rate(wal_buffer_flush_histogram_bucket[1m])))",
     "legendFormat": "P99.9"
    },
    {
     "expr": "histogram_quantile(1, sum by (le) (rate(wal_buffer_flush_histogram_bucket[1m])))",
     "legendFormat": "P100"
    }
   ]
  },
  {
   "title": "Lock wait Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(wal_buffer_lock_wait_histogram_bucket[1m])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(wal_buffer_lock_wait_histogram_bucket[1m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.999, sum by (le) (rate(wal_buffer_lock_wait_histogram_bucket[1m])))",
     "legendFormat": "P99.9"
    },
    {
     "expr": "histogram_quantile(1, sum by (le) (rate(wal_buffer_lock_wait_histogram_bucket[1m])))",
     "legendFormat": "P100"
    }
   ]
  },
  { "title": "BTree", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Writes/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "rate(store_writes_histogram_count[10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Writes Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(store_writes_histogram_bucket[10m])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(store_writes_histogram_bucket[10m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.999, sum by (le) (rate(store_writes_histogram_bucket[10m])))",
     "legendFormat": "P99.9"
    },
    {
     "expr": "histogram_quantile(1, sum by (le) (rate(store_writes_histogram_bucket[10m])))",
     "legendFormat": "P100"
    }
   ]
  },
  {
   "title": "Adds/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum(rate(btree_adds_histogram_count[10s])) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Adds Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(btree_adds_histogram_bucket[10m])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(btree_adds_histogram_bucket[10m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.999, sum by (le) (rate(btree_adds_histogram_bucket[10m])))",
     "legendFormat": "P99.9"
    },
    {
     "expr": "histogram_quantile(1, sum by (le) (rate(btree_adds_histogram_bucket[10m])))",
     "legendFormat": "P100"
    }
   ]
  },
  {
   "title": "Flushes/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "sum(rate(node_store_flush_size_histogram_count[1m])) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flush Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(node_store_flush_size_histogram_bucket[10m])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(node_store_flush_size_histogram_bucket[10m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.999, sum by (le) (rate(node_store_flush_size_histogram_bucket[10m])))",
     "legendFormat": "P99.9"
    },
    {
     "expr": "histogram_quantile(1, sum by (le) (rate(node_store_flush_size_histogram_bucket[10m])))",
     "legendFormat": "P100"
    }
   ]
  },
  {
   "title": "Seeks/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "sum(rate(node_store_seek_size_histogram_count[1m])) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Adds Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum by (le) (rate(btree_add_lock_wait_histogram_bucket[1m])))",
     "legendFormat": "Lock wait"
    },
    {
     "expr": "histogram_quantile(0.999, sum by (le) (rate(btree_add_get_wait_histogram_bucket[1m])))",
     "legendFormat": "Get"
    },
    {
     "expr": "histogram_quantile(0.999, sum by (le) (rate(btree_add_persist_wait_histogram_bucket[1m])))",
     "legendFormat": "Persist"
    },
    {
     "expr": "histogram_quantile(0.999, sum by (le) (rate(btree_add_insert_wait_histogram_bucket[1m])))",
     "legendFormat": "Insert"
    },
    {
     "expr": "histogram_quantile(0.999, sum by (le) (rate(btree_add_remaining_histogram_bucket[1m])))",
     "legendFormat": "Remaining"
    }
   ]
  },
  {
   "title": "Write buffer length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "targets": [
    { "expr": "node_store_buffer_size", "legendFormat": "__auto" }
   ]
  }
 ]
}